# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.1
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z045ffg900-2 ../xilinx_com_hls_mean_value_accel_1_0.zip
